services:
  postgres:
    image: postgres:18
    container_name: postgres-medusa
    environment:
      POSTGRES_USER: medusa-starter
      POSTGRES_PASSWORD: medusa-password
      POSTGRES_DB: medusa-starter
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "medusa-starter"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - medusa-network


  redis:
    image: redis:8
    volumes:
      - cache-backend-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - medusa-network



  backend-server:
    container_name: medusa-app
    image: urgosxd7/medusa-app:latest
    volumes:
      - backend-server-data:/data
    expose:
      - "9000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - medusa-network
      - red-compartida
      - proxiable



volumes:
  postgres-data:
  backend-server-data:
  cache-backend-data:

networks:
  proxiable:
    external: true
    name: proxiable # Asegúrate de que este nombre coincida exactamente con tu red externa
  medusa-network:
    driver: bridge
  red-compartida:
    external: true      # <--- ¡ESTO ES LO IMPORTANTE!
    name: red-compartida # Asegura que busque el nombre exacto
